# Intro to Python

## Hello world

In [1]:
print("Hello world")

Hello world


# Basic Types

### Strings 

In [2]:
my_string = "I'm string"
print(my_string)

I'm string


In [3]:
type(my_string)

str

In [4]:
also_a_string = 'I too am a string'
also_a_string

'I too am a string'

In [5]:
type(also_a_string)

str

In [6]:
multi_line_string = """
I'm on 1
2
3
4 lines
"""
multi_line_string

"\nI'm on 1\n2\n3\n4 lines\n"

In [7]:
type(multi_line_string)

str

#### Operations

##### Concatenation

In [8]:
"a" + "b"

'ab'

#### Indexing and Slicing

In [9]:
"abc"[0]

'a'

In [10]:
"abc"[0:2]

'ab'

In [12]:
"abc"[-2]

'b'

#### Substitution

In [13]:
name = "Mike"

In [14]:
"Hello %s" % name

'Hello Mike'

In [16]:
"Hello {} {}".format(name, "foo")

'Hello Mike foo'

In [17]:
"Hello {name}".format(name=name)

'Hello Mike'

In [18]:
"{0} {1}".format("Hello", name)

'Hello Mike'

In [20]:
f"Hello {len(name)}"

'Hello 4'

#### Length

In [21]:
len("abc")

3

## Integers

In [22]:
my_int = 1
my_int

1

In [23]:
type(my_int)

int

## Floating point numbers

In [24]:
my_float = 1.0
my_float

1.0

In [25]:
type(my_float)

float

#### A note about precision

In [26]:
my_sum = 0.0
for i in range(0, 10):
    my_sum += 0.1
my_sum

0.9999999999999999

### Booleans

In [27]:
my_bool = True
my_bool

True

In [28]:
type(my_bool)

bool

In [29]:
True and False

False

In [30]:
True or False

True

In [31]:
not False

True

### Lists/arrays

In [32]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [33]:
type(my_list)

list

In [34]:
also_a_list = list("abc")
also_a_list

['a', 'b', 'c']

In [35]:
type(also_a_list)

list

#### Operations 

#### Indexing and slicing

In [36]:
my_list[0]

1

In [37]:
my_list[-1]

3

In [38]:
my_list[0:2]

[1, 2]

In [39]:
my_list[0:3:2]

[1, 3]

In [40]:
my_list[::]

[1, 2, 3]

In [42]:
my_list[::-1]

[3, 2, 1]

In [45]:
import pandas as pd
df = pd.DataFrame({'a': my_list})

In [48]:
df

a
0  1
1  2
2  3

In [51]:
df.values[::-1]

array([[3],
       [2],
       [1]])

#### For loop

In [54]:
for i in my_list:
    print(i)

1
2
3


In [59]:
for index, value in enumerate(['a', 'b', 'c']):
    print(f"{index}: {value}")

0: a
1: b
2: c


#### Concatenation

In [60]:
my_list + [4]

[1, 2, 3, 4]

#### Removal

In [61]:
delete_from_list = [1, 2, 3]
del delete_from_list[1]

In [62]:
delete_from_list

[1, 3]

In [63]:
pop_from_end = [1, 2, 3]
pop_from_end.pop()

3

In [64]:
pop_from_end

[1, 2]

In [65]:
pop_from_front = [1, 2, 3]
pop_from_front.pop(0)

1

In [66]:
pop_from_front

[2, 3]

#### Insertion

In [67]:
insert_into_list = [1, 2, 3]
insert_into_list.insert(1, 1.5)
insert_into_list

[1, 1.5, 2, 3]

In [68]:
append_to_end = [1, 2, 3]
append_to_end.append(4)
append_to_end

[1, 2, 3, 4]

#### Test membership

In [69]:
1 in [1, 2, 3]

True

In [70]:
0 in [1, 2, 3]

False

#### List comprehensions and higher order functions

In [71]:
array = [1, 2, 3]
array

[1, 2, 3]

In [72]:
[i * 2 for i in array]

[2, 4, 6]

In [73]:
list(map(lambda i: i * 2, array))

[2, 4, 6]

In [74]:
[i for i in array if i % 2 == 0]

[2]

In [75]:
list(filter(lambda i: i % 2 == 0, array))

[2]

In [77]:
sum(array)

6

In [80]:
min(array)

1

In [81]:
max(array)

3

In [84]:
import functools
functools.reduce(lambda acc, i: acc and i, [True, False, True])


False

#### Matrices

In [85]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [88]:
[item for row in my_matrix for item in row ]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
my_3d_matrix = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
[item for row in my_3d_matrix for col in row for item in col ]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
import numpy as np
np.array(my_3d_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tuples

In [93]:
my_tuple = (1, 2, 3)
my_tuple

(1, 2, 3)

In [94]:
type(my_tuple)

tuple

In [95]:
mixed_type_tuple = (1, 2.0, '3', False)
mixed_type_tuple

(1, 2.0, '3', False)

In [96]:
also_a_tuple = tuple([1, 2, 3])
also_a_tuple

(1, 2, 3)

#### Operations

##### Indexing

In [97]:
my_tuple = (1, 2, 3)
my_tuple[0]

1

##### Unpacking

In [98]:
a, b, c = (1, 2, 3)
print(a, b, c)

1 2 3


### Dictionaries/Maps

In [99]:
my_dict = {"foo": "bar"}
my_dict

{'foo': 'bar'}

In [100]:
type(my_dict)

dict

In [102]:
also_a_dict = dict(foo="bar", one=2)
also_a_dict

{'foo': 'bar', 'one': 2}

In [ ]:
type(also_a_dict)

In [103]:
mixed_type_dict = {'a': 1, 2: False, 3.0: None}
mixed_type_dict

{'a': 1, 2: False, 3.0: None}

#### Map comprehensions

In [104]:
keys = [1, 2, 3]
values = [4, 5, 6]
list(zip(keys, values))

[(1, 4), (2, 5), (3, 6)]

In [107]:
my_dict = {k: v for k, v in zip(keys, values) if k % 2 == 0}
my_dict

{2: 5}

In [109]:
keys = {k for k in keys}

In [110]:
type(keys)

set

#### Operations 

##### Insertion

In [111]:
my_dict = {"foo": "bar"}
my_dict["one"] = 2
my_dict

{'foo': 'bar', 'one': 2}

##### Deletion

In [112]:
my_dict = {"foo": "bar"}
del my_dict["foo"]
my_dict

{}

##### Access by key

In [113]:
my_dict = {"foo": "bar"}
my_dict["foo"]

'bar'

#### Getting the keys

In [114]:
{1: 2, 3: 4}.keys()

dict_keys([1, 3])

##### Getting values

In [115]:
{1: 2, 3: 4}.values()

dict_values([2, 4])

##### Iteration

In [116]:
for key in my_dict:
    print(key)

foo


In [117]:
for key, value in my_dict.items():
    print(key, value)

foo bar


##### Concatenation

In [118]:
my_dict = {"foo": "bar"}
my_dict.update({1: 2})
my_dict

{'foo': 'bar', 1: 2}

#### Testing key in dictionary

In [119]:
"foo" in {"foo": "bar"}

True

### Nones/Nulls

In [120]:
my_none = None
my_none

In [121]:
type(my_none)

NoneType

#### Testing for none

In [122]:
my_var = 1
my_var is None

False

In [123]:
my_var = None
my_var is None

True

### Functions 

In [124]:
def my_func(a, b):
    return a + b

In [125]:
type(my_func)

function

In [126]:
my_func(1, 2)

3

In [128]:
my_func(b=1, a=2)

3

In [129]:
my_func(1, b=2)

3

In [130]:
my_func(*(1, 2))

3

In [131]:
my_func(**{"a": 1, "b": 2})

3

In [132]:
my_func(1., 2)

3.0

In [133]:
my_func("a", "b")

'ab'

In [134]:
my_func([1, 2, 3], [4, 5, 6])

[1, 2, 3, 4, 5, 6]

In [135]:
my_func({"foo": "bar"}, {1: 2})

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [136]:
def multiple_return():
    return 1, 2, 3

In [138]:
output = multiple_return()
type(output)

tuple

In [139]:
output

(1, 2, 3)

### Lambas (a.k.a short functions)

In [140]:
lambda_func = lambda a, b: a + b

In [141]:
type(lambda_func)

function

In [142]:
lambda_func(1, 2)

3

#### IMPORTANT
In Python, functions are objects too!

In [143]:
simple_dict = {5: 4, 2: 1, 3: 5, 10: 1}
simple_dict

{5: 4, 2: 1, 3: 5, 10: 1}

In [144]:
def sum_obj(my_obj, sum_op):
    return sum_op(my_obj)

In [145]:
sum(simple_dict.keys())

20

In [146]:
sum_obj(simple_dict, sum)

20

In [147]:
sum(simple_dict.values())

11

In [148]:
sum_obj(simple_dict, lambda d: sum(d.values()))

11

## Libraries (aka modules)

### Basic import

In [149]:
import math

In [150]:
math.pi

3.141592653589793

### Named import

In [151]:
import numpy as np

In [152]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

### Import submodule

In [153]:
from datetime import datetime, timedelta
datetime.now()

datetime.datetime(2022, 9, 13, 21, 11, 12, 32456)

In [154]:
datetime.now() + timedelta(days=1)

datetime.datetime(2022, 9, 14, 21, 11, 35, 279686)

## Classes

In [4]:
class Foo:
    my_static_variable = 0
    
    def __init__(self, arg1, arg2='default'):
        # constructor
        self.bar = arg1
        self.optional = arg2
        self._protected_attr = 'protected'
        self.__private_attr = 'private'
        
    def __str__(self):
        # to string method
        return f"bar={self.bar}; optional={self.optional}; __private_attr={self.__private_attr}; _protected_attr={self._protected_attr}"
    
    
    def size_bar(self):
        return len(str(self.bar))
    
    @staticmethod
    def static_method():
        return 1 + 2
    
    @classmethod
    def update(cls):
        cls.my_static_variable += 1
        

In [5]:
Foo.my_static_variable

0

In [6]:
Foo.static_method()

3

In [7]:
Foo.update()
Foo.my_static_variable

1

In [8]:
my_foo = Foo(1)
str(my_foo)

'bar=1; optional=default; __private_attr=private; _protected_attr=protected'

In [9]:
my_foo.bar

1

In [10]:
my_foo.bar = 2

In [11]:
my_foo.bar + 1

3

In [12]:
my_foo._protected_attr

'protected'

In [13]:
another_foo = Foo(2, "bar")
str(another_foo)

'bar=2; optional=bar; __private_attr=private; _protected_attr=protected'

In [14]:
my_foo.size_bar()

1

### Inheritance

In [15]:
class Bar(Foo):
    def __init__(self, arg1):
        super().__init__(arg1)
    
    def size_bar(self):
        return super().size_bar() + 1

In [16]:
bar = Bar(3)

In [17]:
print(bar)

bar=3; optional=default; __private_attr=private; _protected_attr=protected


In [18]:
bar.size_bar()

2

### Multiple Inheritance

In [19]:
class A:
    pass
class B:
    pass
class C(A, B):
    pass

In [20]:
a = A()

In [21]:
isinstance(a, A)

True

In [22]:
isinstance(a, B)

False

In [23]:
isinstance(a, C)

False

In [24]:
c = C()

In [25]:
isinstance(c, A)

True

In [26]:
isinstance(c, B)

True

In [27]:
isinstance(c, C)

True

In [ ]:
type(c)

In [29]:
class D:
    def call(self):
        return 'd'
class E:
    def call(self):
        return 'e'
class DE(D, E):
    pass
class ED(E, D):
    pass

In [30]:
D().call()

'd'

In [31]:
E().call()

'e'

In [32]:
DE().call()

'd'

In [33]:
ED().call()

'e'

## Control Flow

### If/Else

In [34]:
def test_num(a):
    if type(a) not in [int, float]:
        raise ValueError(f"Invalid input: {a}")
    if a < 0:
        return "Negative"
    elif a > 0:
        return "Positive"
    else:
        return "Neither"

In [35]:
test_num(-1)

'Negative'

In [36]:
test_num(0)

'Neither'

In [37]:
test_num(1)

'Positive'

In [38]:
test_num('a')

ValueError: Invalid input: a

In [40]:
output = True if True == False else False
output

False

#### Falsy values

In [41]:
if False:
    print("True")

In [42]:
if "":
    print("True")

In [43]:
if None:
    print("True")

In [44]:
if 0:
    print("True")

In [ ]:
if []:
    print("True")

In [ ]:
if {}:
    print("True")

In [ ]:
if tuple():
    print("True")

#### Loops

In [ ]:
counter = 3
while counter > 0:
    print(counter)
    counter -= 1

In [ ]:
for i in range(3):
    print(i)